docker:
  HOST: unix:///var/run/docker.sock
messager:
  PUB_ADDRESS: tcp://127.0.0.1:22550
  PULL_ADDRESS: tcp://127.0.0.1:22549
postgres:
  HOST: /var/run/postgresql/.s.PGSQL.5432
  PORT: null
  USER: null
  DATABASE: null
  PASSWORD: null
redis:
  DSN: /var/run/redis/redis.sock
  PASSWORD: null
webapi:
  GAME_HOST: localhost
  GAME_PORT_RANGE_START: 23000
  GAME_PORT_RANGE_STOP: 24000
  GROUP_URL: http://localhost:22548/v1/groups
  HOST: localhost
  JWT_EXPIRATION_TIME: 12h
  JWT_SECRET: super-secret-password
  LOG_LEVEL: WARNING
  MSGQUEUES_URL: http://localhost:22548/v1/msgqueues
  PORT: 22548
  PRODUCTION: false
  SSL_CERT_PATH: null
  SSL_KEY_PASS: null
  SSL_KEY_PATH: null
